# -*- coding: utf-8 -*-
"""Linear Models in R_the insulate case study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HwOyEOwAoCqZT7plWmRmG6nmA9RIMNAA
"""

########################################################
#Model with python style results
########################################################
import pandas as pd
import statsmodels.formula.api as smf

df1 = pd.read_csv("Data/insulate_data.txt", sep=r"\s+", header=None, names=["quando", "temp", "cons"])

regr = smf.ols('cons ~ quando + temp', data=df1).fit()
print(regr.summary())


ci = regr.conf_int(alpha=0.05)
ci.columns = ["2.5%", "97.5%"]
print(ci)



print("*******************************************************************************************")
print("- AIC (Akaike Information Criterion): measures model fit penalized by number of parameters; lower is better for predictive accuracy.")
print("- BIC (Bayesian Information Criterion): similar but penalizes complexity more strongly (penalty grows with sample size); lower is better for selecting a simpler, more parsimonious model.")
print("- Omnibus = 0.568, Prob(Omnibus) = 0.753 — the omnibus test for normality of residuals is not significant, so there is no evidence against normality.")
print("- Jarque–Bera (JB) = 0.707, Prob(JB) = 0.702 — the JB test also fails to reject normality, consistent with the Omnibus result.")
print("- Skew = -0.171 — residuals show a very small negative skew (close to symmetric).")
print("- Kurtosis = 2.569 — slightly below 3, so residuals are mildly platykurtic (lighter tails than a normal distribution), but the deviation is small.")
print("- Durbin–Watson = 1.500 — this is below 2 and suggests some positive autocorrelation in residuals (not extreme, but worth checking).")
print("- Cond. No. = 13.6 — condition number is low; no sign of severe multicollinearity.")
print("*******************************************************************************************")

########################################################
#Model with R style results
########################################################
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

df = pd.read_csv("Data/insulate_data.txt", sep=r"\s+", header=None, names=["quando", "temp", "cons"])

regr = smf.ols('cons ~ quando + temp', data=df).fit()

# RESIDUALS SUMMARY (R style)
res = regr.resid

print("## Residuals:")
print("Min", np.min(res))
print("1Q", np.percentile(res, 25))
print("Median", np.median(res))
print("3Q", np.percentile(res, 75))
print("Max", np.max(res))


# COEFFICIENTS TABLE
print("\n## Coefficients:")

coef_table = pd.DataFrame({
    "Estimate": regr.params,
    "Std. Error": regr.bse,
    "t value": regr.tvalues,
    "Pr(>|t|)": regr.pvalues
})

print(coef_table)


# RESIDUAL STANDARD ERROR
rse = np.sqrt(regr.scale)

print("\nResidual standard error:", round(rse, 4), "on", int(regr.df_resid), "degrees of freedom")


# R-SQUARED
print("Multiple R-squared:", round(regr.rsquared, 4))
print("Adjusted R-squared:", round(regr.rsquared_adj, 4))


# F-STATISTIC
print("F-statistic:", round(regr.fvalue, 1),
      "on", int(regr.df_model), "and", int(regr.df_resid),
      "DF, p-value:", regr.f_pvalue)

ci1 = regr.conf_int(alpha=0.05)
ci1.columns = ["2.5%", "97.5%"]
ci1

#PLOT#####################################################
import matplotlib.pyplot as plt  # import plotting library

res = regr.resid  # extract residuals (observed - fitted values)
plt.scatter(df["temp"], res, color="purple")  # plot residuals vs temperature
plt.xlabel("temp")  # label for x-axis (temperature)
plt.ylabel("residuals")  # label for y-axis (residuals)
plt.show()  # display the plot

#PLOT#####################################################
import matplotlib.pyplot as plt  # import plotting library

prima = df[df["quando"] == "prima"]  # select rows where insulation = "prima"
dopo = df[df["quando"] == "dopo"]    # select rows where insulation = "dopo"

plt.scatter(prima["temp"], prima["cons"], label="prima")  # plot points for "prima"
plt.scatter(dopo["temp"], dopo["cons"], label="dopo")     # plot points for "dopo"

b0 = regr.params["Intercept"]        # intercept of the model (baseline: "dopo")
b_temp = regr.params["temp"]         # slope for temperature
b_q = regr.params.get("quando[T.prima]", 0)  # effect of "prima" (shift in intercept)

x = df["temp"]  # x-values (temperature)

plt.plot(x, b0 + b_temp*x, linewidth=2)            # regression line for "dopo"
plt.plot(x, (b0 + b_q) + b_temp*x, linewidth=2)    # regression line for "prima"

plt.title("With and without insulation (parallel lines)")  # plot title
plt.xlabel("temperatura")  # x-axis label
plt.ylabel("consumo")      # y-axis label
plt.legend()               # show legend (prima vs dopo)
plt.show()                 # display the plot

#########################################################
#Model considering the Interaction (with R style results)
#########################################################
regr2 = smf.ols('cons ~ quando * temp', data=df1).fit() #The * operator is not multiplication. It’s a shortcut operator that expands into main effects, and their interaction.

# RESIDUALS SUMMARY (R style)
res2 = regr2.resid

print("## Residuals:")
print("Min", np.min(res2))
print("1Q", np.percentile(res2, 25))
print("Median", np.median(res2))
print("3Q", np.percentile(res2, 75))
print("Max", np.max(res2))


# COEFFICIENTS TABLE
print("\n## Coefficients:")

coef_table = pd.DataFrame({
    "Estimate": regr2.params,
    "Std. Error": regr2.bse,
    "t value": regr2.tvalues,
    "Pr(>|t|)": regr2.pvalues
})

print(coef_table)


# RESIDUAL STANDARD ERROR
rse = np.sqrt(regr2.scale)

print("\nResidual standard error:", round(rse, 4), "on", int(regr2.df_resid), "degrees of freedom")


# R-SQUARED
print("Multiple R-squared:", round(regr2.rsquared, 4))
print("Adjusted R-squared:", round(regr2.rsquared_adj, 4))


# F-STATISTIC
print("F-statistic:", round(regr2.fvalue, 1),
      "on", int(regr2.df_model), "and", int(regr2.df_resid),
      "DF, p-value:", regr2.f_pvalue)

ci = regr2.conf_int(alpha=0.05)
ci.columns = ["2.5%", "97.5%"]
ci

#PLOT#####################################################
import matplotlib.pyplot as plt  # plotting

res2 = regr2.resid  # residuals from model with interaction
plt.scatter(df1["temp"], res2, color="purple")  # residuals vs temperature
plt.xlabel("temp")
plt.ylabel("residuals")
plt.show()

#PLOT#####################################################
import matplotlib.pyplot as plt  # plotting

prima = df1[df1["quando"] == "prima"]  # subset: prima
dopo = df1[df1["quando"] == "dopo"]    # subset: dopo

plt.scatter(prima["temp"], prima["cons"], label="prima")  # points prima
plt.scatter(dopo["temp"], dopo["cons"], label="dopo")     # points dopo

b0 = regr2.params["Intercept"]            # base intercept (dopo)
b_temp = regr2.params["temp"]             # slope for temp (dopo)
b_q = regr2.params.get("quando[T.prima]", 0)          # intercept shift (prima)
b_int = regr2.params.get("quando[T.prima]:temp", 0)   # slope change (interaction)

x = df1["temp"]  # x values

plt.plot(x, b0 + b_temp*x, linewidth=2)                      # line for dopo
plt.plot(x, (b0 + b_q) + (b_temp + b_int)*x, linewidth=2)    # line for prima (different slope)

plt.title("With and without insulation (interaction model)")
plt.xlabel("temperatura")
plt.ylabel("consumo")
plt.legend()
plt.show()